service:
  name: slack-animal-bot

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  timeout: 20
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource: "*"
  environment:
    SKACK_INCOMING_WEBHOOK_URL: ${ssm:/slack.incoming_webhooks.cat~true}
    FLICKER_API_KEY: ${ssm:/flicker.apikey~true}

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: SlackAnimalBot

functions:
  responseToSlackMessage:
    name: response-to-slack-message-${self:provider.stage}
    handler: src/index.handler
    events:
      - http:
          path: animal_api
          method: POST
