service:
  name: slack-animal-bot

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  timeout: 20

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: SlackAnimalBot

functions:
  searchAndPostAnimalImage:
    name: search-and-post-animal-image
    handler: src/index.searchAndPostAnimalImage
    events:
      - http:
          path: animal_api
          method: POST
